samples: "config/samples.tsv"
genome:
  build: "<genome-name>" # id for the genome
  fasta: "<path-to-genome.fastq>" # path to genome .fasta
  annotation: "<path-to-transcriptome-annotation>.gtf" # path to transcripts.gtf